name: CI

'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - '14.18.1'

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Set up Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v2
        with:
          node-version: '${{ matrix.node-version }}'

      - name: 'Install dependencies'
        uses: borales/actions-yarn@v2.0.2
        with:
          cmd: install

      - name: 'Code lint'
        uses: borales/actions-yarn@v2.0.2
        with:
          cmd: lint

      - name: 'Build project'
        uses: borales/actions-yarn@v2.0.2
        with:
          cmd: build

      - name: 'Make executable script'
        run: chmod +x bin/toster-tags-parser

      # - name: 'Run tests'
      #   uses: borales/actions-yarn@v2.0.2
      #   with:
      #     cmd: test

      - name: 'Show version'
        run: bin/toster-tags-parser --version

      - name: 'Show help'
        run: bin/toster-tags-parser --help

      - name: 'Parse first page'
        run: bin/toster-tags-parser --pages 1 --output ./assets/tags.json
